use_frameworks!

target 'StoryboardLoadable_Example' do
  pod 'StoryboardLoadable', :path => '../'

  target 'StoryboardLoadable_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
